// <auto-generated />
using System;
using ClosureService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClosureService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260219175135_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClosureService.Domain.Models.Foreclosure", b =>
                {
                    b.Property<int>("ForeclosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForeclosureId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CertificateGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("CertificatePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ForeclosureCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ForeclosureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ForeclosureType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InterestOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PenaltyOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RebateAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemainingTenure")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("SavingsAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ForeclosureId");

                    b.ToTable("Foreclosures");
                });

            modelBuilder.Entity("ClosureService.Domain.Models.LoanClosure", b =>
                {
                    b.Property<int>("ClosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClosureId"));

                    b.Property<DateTime?>("ActualMaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosureApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosureCertificatePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ClosureCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosureStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NocFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NocIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NocIssued")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NocNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OriginalMaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OutstandingAtClosure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RebateAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SettlementAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDisbursed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalInterestPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPenaltyPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrincipalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WriteOffAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ClosureId");

                    b.ToTable("LoanClosures");
                });
#pragma warning restore 612, 618
        }
    }
}
