// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanctionsAndDisbursementService.Infrastructure.Data;

#nullable disable

namespace SanctionsAndDisbursementService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260217194733_UpdatedDecimalforloanamount")]
    partial class UpdatedDecimalforloanamount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanctionsAndDisbursementService.Domain.Models.Disbursement", b =>
                {
                    b.Property<int>("disbursementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("disbursementId"));

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("createdBy")
                        .HasColumnType("int");

                    b.Property<int>("dealId")
                        .HasColumnType("int");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("disburseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("disburseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("modifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<Guid>("transactionReference")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("disbursementId");

                    b.ToTable("Disbursements");
                });

            modelBuilder.Entity("SanctionsAndDisbursementService.Domain.Models.Sanction", b =>
                {
                    b.Property<int>("sanctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sanctionId"));

                    b.Property<DateTime?>("acceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("createdBy")
                        .HasColumnType("int");

                    b.Property<bool>("customerAccepted")
                        .HasColumnType("bit");

                    b.Property<int>("dealId")
                        .HasColumnType("int");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("emiAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("interestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("loanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("modifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("pdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("repaymentSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("sanctionNo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("tenureMonths")
                        .HasColumnType("int");

                    b.HasKey("sanctionId");

                    b.ToTable("Sanctions");
                });
#pragma warning restore 612, 618
        }
    }
}
