// <auto-generated />
using System;
using LoanTable.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanTable.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216112155_LoansTables")]
    partial class LoansTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanTable.Domain.Model.LoanTables", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DisbursedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DisbursementDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstEmiDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextEmiDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<int>("dealId")
                        .HasColumnType("int");

                    b.Property<int>("disbursementId")
                        .HasColumnType("int");

                    b.Property<int>("dpd")
                        .HasColumnType("int");

                    b.Property<decimal>("emiAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("emiDay")
                        .HasColumnType("int");

                    b.Property<decimal>("interestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("loanTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("maturityDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("outstandingInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("outstandingPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("remainingTenure")
                        .HasColumnType("int");

                    b.Property<int>("sanctionId")
                        .HasColumnType("int");

                    b.Property<string>("sanctionNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("sanctionedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("scoreCardId")
                        .HasColumnType("int");

                    b.Property<int>("tenureMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("totalOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LoanId");

                    b.ToTable("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
